const fs=require('fs'),vm=require('vm');
const source=fs.readFileSync('design-assets/service-design-injection.html','utf8');
let css=source.match(/<style[^>]*>([\s\S]*?)<\/style>/)[1];
css+=`\n.sch-detail h1>span:last-child{min-width:0}.sch-detail .fa-fan:before{content:"\\f863"}.sch-detail .fa-burn:before{content:"\\f46a"}.sch-detail .fa-tools:before{content:"\\f7d9"}.sch-detail a:focus-visible{outline:3px solid #50adeb;outline-offset:4px}.sch-detail__contact h2,.sch-detail__copy h2,.sch-detail h1{text-transform:none!important}.sch-detail__image>img:not(.sch-image-watermark){aspect-ratio:3/2}.sch-detail__title-icon{font-family:"Font Awesome 5 Free"}.sch-detail__contact-meta{text-align:left!important}.sch-service-card .sch-image-watermark{transition:none!important;transform:none!important;object-fit:contain!important}.sch-detail__image .sch-image-watermark{min-height:0!important;height:auto!important;aspect-ratio:auto!important}.sch-service-card__media .sch-image-label{font-size:10px}.sch-detail__image>img:not(.sch-image-watermark){min-height:0!important;height:auto!important;align-self:center;object-fit:contain!important}.sch-detail__image{display:flex;align-items:center;background:#eef2f5;min-width:0}@media(max-width:600px){.sch-detail__image{min-height:0!important}.sch-detail h1{font-size:30px!important}.sch-detail__image .sch-image-watermark{width:52%!important}.sch-service-card .sch-image-watermark{width:80%!important;right:8px;top:8px}.sch-service-card .sch-image-label{font-size:9px;padding:3px 5px;right:6px;bottom:6px}.sch-service-card__icon{bottom:8px!important;left:8px!important}}`;
let js=source.match(/<script[^>]*>([\s\S]*?)<\/script>/)[1];
js=js.replace('neubauinstallationen-symbolbild.webp','neubau-planung-symbolbild-v2.webp').replace('sanierungsarbeiten-symbolbild.webp','sanierung-heizkoerper-symbolbild-v2.webp').replace('Symbolbild einer Rohinstallation im Neubau','Symbolbild einer Installationsplanung im Neubau').replace('Symbolbild einer fachgerechten Haustechnik-Sanierung','Symbolbild eines erneuerten Heizkörpers bei einer Sanierung');
// Access the already prepared config inside a bounded local renderer, not on live site.
js=js.replace("var steps=", "globalConfig=services;var steps=");
const ids=[63,68,76,83,88,126,96,99];
const slugs=['waermepumpen','pelletskessel','gasgeraete','klimaanlage-und-klimaanlagenservice','neubauinstallationen','sanierungsarbeiten','badezimmer-und-badzimmersanierung','kleine-reparaturen-und-installationen'];
if(fs.existsSync('design-assets/deployment/final.css')) css=fs.readFileSync('design-assets/deployment/final.css','utf8');
const package={css:'<style id="sch-service-detail-styles">'+css.replace(/\n/g,'')+'</style>',pages:[],maps:{}};
slugs.forEach((slug,idx)=>{let el={innerHTML:''};let sandbox={location:{pathname:'/'+slug+'/'},document:{readyState:'complete',querySelector:()=>el,querySelectorAll:()=>[]}};vm.runInNewContext(js,sandbox);let config=sandbox.globalConfig['/'+slug+'/'];const titles=['Wärmepumpen','Pelletskessel','Gasgeräte','Klimaanlagen','Neubau','Sanierungen','Badezimmer','Reparaturen'];let html=el.innerHTML.replace(config.title,titles[idx]);html=html.replace('<span class="sch-detail__title-icon"','<span class="sch-detail__title-icon sch-page-service-icon"');html=html.replace('fetchpriority="high"','fetchpriority="high" decoding="async"');const wrapped='[fusion_builder_container type="flex" hundred_percent="yes" padding_top="0px" padding_bottom="0px" padding_left="0px" padding_right="0px"][fusion_builder_row][fusion_builder_column type="1_1" margin_bottom="0px" spacing_left="0px" spacing_right="0px"][fusion_text margin_bottom="0px"]'+html+'[/fusion_text][/fusion_builder_column][/fusion_builder_row][/fusion_builder_container]';package.pages.push({id:ids[idx],slug,html,content:wrapped,meta:config.lead+' Beratung und Montage von Schmolengruber Installationen in Schönkirchen-Reyersdorf.'});package.maps['/'+slug+'/']={image:config.image,alt:config.alt};fs.writeFileSync('design-assets/deployment/'+ids[idx]+'.txt',wrapped);});
fs.writeFileSync('design-assets/deployment/package.json',JSON.stringify(package));
fs.writeFileSync('design-assets/deployment/package.html','<!doctype html><meta charset="utf-8"><pre id="package">'+JSON.stringify(package).replace(/&/g,'&amp;').replace(/</g,'&lt;')+'</pre>');
console.log('Prepared',package.pages.length,'static WordPress pages and shared CSS');
